name: SAP-ALIVE-ALL

on:
  schedule:
    # SAP BTP SPACE每天0:0-10期间STOP
    # 重点每天UTC0:0-1执行，其他时间测试，可删除
    # 因github实际执行延迟可能超100分钟，提前一小时增加一次触发
    - cron: '10 23,0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  restart-apps:
    runs-on: ubuntu-latest
    #runs-on: self-hosted # 使用标签为self-hosted的Runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CF CLI
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install -y cf-cli

      - name: Login to US
        env:
          CF_API_URL: https://api.cf.us10-001.hana.ondemand.com  # 替换为你的API端点
          CF_USERNAME: ${{ secrets.CF_USERNAME }}     # 在gh-setting-secrets填入服务器帐号信息
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: t2_t2-mcekz8t8
          CF_SPACE: dev
        run: |
          cf login -a $CF_API_URL -u $CF_USERNAME -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE

      - name: Restart Apps
        run: |
          # 重启应用
          cf restart "s3"


      - name: Login to SG
        env:
          CF_API_URL: https://api.cf.ap21.hana.ondemand.com  # 替换为你的API端点
          CF_USERNAME: ${{ secrets.CF_USERNAME }}           # GitHub Secrets存储凭据
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: fde1f680trial
          CF_SPACE: dev
        run: |
          cf login -a $CF_API_URL -u $CF_USERNAME -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE

      - name: Restart Apps
        run: |
          # 重启应用
          cf restart "iSAP"  
